"""Local reference style blueprint for the hackathon MP4.

This is a deterministic stand-in for the future model-extracted StyleTemplate.
It lets the rest of the pipeline move now while Fal video-understanding prompts
and span merging mature.
"""

REFERENCE_CUT_CANDIDATES = [
    7.200,
    8.167,
    8.967,
    9.900,
    11.000,
    21.400,
    24.867,
    26.767,
    28.500,
    35.567,
    36.500,
    37.367,
    38.200,
    39.033,
    41.933,
    42.600,
    43.500,
    44.467,
    45.300,
    46.267,
    47.167,
    48.000,
    53.433,
    54.267,
    55.067,
    56.533,
    57.633,
    58.567,
    60.467,
    64.167,
    66.367,
    66.933,
    68.367,
    69.967,
    71.800,
    72.933,
    74.867,
    82.100,
    84.033,
    85.733,
]


STYLE_BLUEPRINT = [
    {
        "id": "shot_001",
        "reference_time": [0.0, 4.0],
        "stylistic_function": "establishing_hero",
        "space_type": "aerial",
        "features": ["roofline", "lot", "setting"],
        "shot_scale": "aerial",
        "composition": "high oblique drone view that establishes the property and surrounding land",
        "camera": {"movement_type": "drone", "direction": "forward drift", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "raw_passthrough",
        "transition_out": "cut",
        "duration": 4.0,
    },
    {
        "id": "shot_002",
        "reference_time": [4.0, 8.2],
        "stylistic_function": "property_reveal",
        "space_type": "aerial",
        "features": ["front elevation", "driveway", "roofline"],
        "shot_scale": "aerial",
        "composition": "wide exterior reveal with the home centered and readable",
        "camera": {"movement_type": "drone", "direction": "lateral drift", "speed": "slow", "path_shape": "arc"},
        "variant_mode": "raw_passthrough",
        "transition_out": "cut_on_beat",
        "duration": 4.2,
    },
    {
        "id": "shot_003",
        "reference_time": [8.2, 11.0],
        "stylistic_function": "arrival",
        "space_type": "exterior",
        "features": ["front elevation", "entry", "driveway"],
        "shot_scale": "wide",
        "composition": "ground-level or low exterior arrival shot with clean architectural lines",
        "camera": {"movement_type": "push_in", "direction": "toward entry", "speed": "medium", "path_shape": "linear"},
        "variant_mode": "conservative_edit",
        "transition_out": "flash_or_hard_cut",
        "duration": 2.8,
    },
    {
        "id": "shot_004",
        "reference_time": [11.0, 13.4],
        "stylistic_function": "energy_accent",
        "space_type": "exterior",
        "features": ["setting", "approach", "landscape"],
        "shot_scale": "wide",
        "composition": "fast exterior context beat used as a bridge between hero and interior",
        "camera": {"movement_type": "truck_right", "direction": "right", "speed": "medium", "path_shape": "linear"},
        "variant_mode": "raw_passthrough",
        "transition_out": "cut_on_beat",
        "duration": 2.4,
    },
    {
        "id": "shot_005",
        "reference_time": [28.5, 35.6],
        "stylistic_function": "space_orientation",
        "space_type": "living",
        "features": ["windows", "seating", "open plan"],
        "shot_scale": "wide",
        "composition": "wide interior orientation with verticals preserved and room flow visible",
        "camera": {"movement_type": "truck_right", "direction": "right", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "cinematic_light_variant",
        "transition_out": "cut",
        "duration": 4.0,
    },
    {
        "id": "shot_006",
        "reference_time": [35.6, 39.0],
        "stylistic_function": "feature_showcase",
        "space_type": "living",
        "features": ["fireplace", "seating", "windows"],
        "shot_scale": "medium",
        "composition": "medium interior feature shot with foreground parallax",
        "camera": {"movement_type": "push_in", "direction": "forward", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "cinematic_light_variant",
        "transition_out": "cut_on_beat",
        "duration": 2.6,
    },
    {
        "id": "shot_007",
        "reference_time": [42.6, 46.3],
        "stylistic_function": "feature_showcase",
        "space_type": "kitchen",
        "features": ["island", "cabinetry", "appliances"],
        "shot_scale": "wide",
        "composition": "kitchen reveal with island or cabinetry anchoring the frame",
        "camera": {"movement_type": "truck_right", "direction": "right", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "cinematic_light_variant",
        "transition_out": "cut",
        "duration": 3.0,
    },
    {
        "id": "shot_008",
        "reference_time": [46.3, 48.0],
        "stylistic_function": "texture_detail",
        "space_type": "detail",
        "features": ["wood", "stone", "fixture", "cabinetry"],
        "shot_scale": "detail",
        "composition": "tight architectural detail used as a visual texture beat",
        "camera": {"movement_type": "push_in", "direction": "forward", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "detail_crop",
        "transition_out": "cut_on_beat",
        "duration": 1.7,
    },
    {
        "id": "shot_009",
        "reference_time": [53.4, 56.5],
        "stylistic_function": "light_moment",
        "space_type": "bathroom",
        "features": ["mirror", "vanity", "window", "fixture"],
        "shot_scale": "medium",
        "composition": "clean bath or vanity moment with bright but controlled highlights",
        "camera": {"movement_type": "push_in", "direction": "forward", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "cinematic_light_variant",
        "transition_out": "cut",
        "duration": 2.5,
    },
    {
        "id": "shot_010",
        "reference_time": [56.5, 60.5],
        "stylistic_function": "breather",
        "space_type": "bedroom",
        "features": ["bed", "window", "quiet room"],
        "shot_scale": "wide",
        "composition": "calmer private-space shot with readable room layout",
        "camera": {"movement_type": "dolly_in", "direction": "forward", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "raw_passthrough",
        "transition_out": "cut",
        "duration": 3.0,
    },
    {
        "id": "shot_011",
        "reference_time": [68.4, 72.9],
        "stylistic_function": "amenity_proof",
        "space_type": "amenity",
        "features": ["outdoor living", "patio", "yard", "view"],
        "shot_scale": "wide",
        "composition": "amenity or outdoor-living proof shot that expands the value of the home",
        "camera": {"movement_type": "crane_up", "direction": "up", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "conservative_edit",
        "transition_out": "cut_on_beat",
        "duration": 3.4,
    },
    {
        "id": "shot_012",
        "reference_time": [88.0, 92.0],
        "stylistic_function": "closing_hero",
        "space_type": "exterior",
        "features": ["front elevation", "setting", "hero"],
        "shot_scale": "wide",
        "composition": "final exterior hero with confident, cinematic framing",
        "camera": {"movement_type": "pull_out", "direction": "backward", "speed": "slow", "path_shape": "linear"},
        "variant_mode": "cinematic_light_variant",
        "transition_out": "fade_or_title_plate",
        "duration": 4.0,
    },
]
